### ISSUE TITLE
WiFly Board doesnt send UDP Packets when sending to Gateway

### ISSUE THREAD

**Issue by mrst0n3** [harlequin-tech/WiFlyHQ#38]
Hi I tried to send some UDP Data to my Router via the Example Code. When I send Data to my own PC in the Network, the Data gets sent, but when I set the IP to xxx.xxx.x.1 No Data is transmitted. Wireshark doesnt see any Packets either. When I send some Data from my PC to the Router it works, and i see the Packages with Wireshark. What am I doing wrong?

**Comment by harlequin-tech** [comment]
@mrst0n3 did you get this working?

**Comment by mrst0n3** [comment]
@harlequin-tech No, I just decided I do not care anymore and did not want this ticket to be in my open issues tab.
