### ISSUE TITLE
failed to get prompt

### ISSUE THREAD

**Issue by anshul119** [harlequin-tech/WiFlyHQ#42]
I'm using RN-XV (Rev 3) with Arduino Uno (R3). Everytime I want to connect to any website I get this message "Failed to get prompt". Any help would be appreciated.

**Comment by quique123** [comment]
It fails quite often.  And if you track it down, reboot is not called out in the library Wifly.cpp in the open().  You must call it and even then, it seems that its not enough, you must reset the arduino as well.  I havent tracked down exactly why the wifi module doesnt reboot enough.  I've made some workarounds after weeks of fiddling with it and Id like to upload my code but im not that familiar with github yet.

**Comment by anshul119** [comment]
Thank you @quique123 :) I resolved the problem way back.

**Comment by quique123** [comment]
OK thanks, you mean your fork of this library?

MV

**Comment by anshul119** [comment]
here: https://github.com/anshul119/wifly_RFID

**Comment by quique123** [comment]
Thanks.  From what I can see in your sketch, you added a wifly.terminal() call after the wifly fails to get prompt which means it fails to connect.  Is that it?
