### ISSUE TITLE
Multiple Access

### ISSUE THREAD

**Issue by michaelaraujo** [harlequin-tech/WiFlyHQ#43]
I have read the documentation, and I know that is allowed only one access at a time using the library, but when I make a request via the web browser the time for another client to perform access to RN-VX is 5 minutes, however I'm using an app developed for Android, and when I make the request via the app time to access new never expires why?
Using an app via Android is only possible to perform a new customer if I restart the Arduino.
I need help. 
Thank you.

**Comment by harlequin-tech** [comment]
The WiFly only supports one connection at a time.  You need to be sure to close the connection when the current client is done.
