### ISSUE TITLE
ttfb is too high

### ISSUE THREAD

**Issue by isaccjr** [harlequin-tech/WiFlyHQ#46]
i'm trying to make a server to read the analogs e digital ports of the arduino. it all ready works, but the ttfb is too high. i'm getting 1,4 seconds per request and I don't know what to do to make it goes faster. I   need less than 1s this 400 ms is really boring me up.

 here is the code

#undef PROGMEM 
#define PROGMEM __attribute__(( section(".progmem.data") )) 
#undef PSTR 
#define PSTR(s) (__extension__({static prog_char __c[] PROGMEM = (s); &__c[0];})) 

#include <WiFlyHQ.h>

#include <SoftwareSerial.h>
SoftwareSerial wifiSerial(4,5);

#include <SPI.h> //essa
String httpRequest; //led pin

#define ledPin 3 //led pin

WiFly wifly;

/* Change these to match your WiFi network */
//const char mySSID[] = "";
//const char myPassword[] = "";

const char mySSID[] = "";
const char myPassword[] = "";

void sendIndex();
void send404();
void mostra_valores();
char buf[1024];

boolean ledstatus = false;

void setup()
{
    
    pinMode(3, OUTPUT); // DEFINICAO SAIDA PARA O LED
    Serial.begin(115200);
   // Serial.begin(9600);
    Serial.println(F("Starting"));
    Serial.print(F("Free memory: "));
    Serial.println(wifly.getFreeMemory(),DEC);
    
   

    wifiSerial.begin(9600);
    if (!wifly.begin(&wifiSerial, &Serial)) {
        Serial.println(F("Failed to start wifly"));
  wifly.terminal();
    }

    /* Join wifi network if not already associated */
    if (!wifly.isAssociated()) {
  /* Setup the WiFly to connect to a wifi network */
  Serial.println(F("Joining network"));
  wifly.setSSID(mySSID);
  wifly.setPassphrase(myPassword);
  wifly.enableDHCP();
  wifly.save();

  if (wifly.join()) {
      Serial.println(F("Joined wifi network"));
  } else {
      Serial.println(F("Failed to join wifi network"));
      wifly.terminal();
  }
    } else {
        Serial.println(F("Already joined network"));
    }

    wifly.setBroadcastInterval(0);  // Turn off UPD broadcast

    //wifly.terminal();

    Serial.print(F("MAC: "));
    Serial.println(wifly.getMAC(buf, sizeof(buf)));
    Serial.print(F("IP: "));
    Serial.println(wifly.getIP(buf, sizeof(buf)));

    wifly.setDeviceID("Wifly-WebServer");

    if (wifly.isConnected()) {
        Serial.println(F("Old connection active. Closing"));
  wifly.close();
    }

    wifly.setProtocol(WIFLY_PROTOCOL_TCP);
    if (wifly.getPort() != 80) {
        wifly.setPort(80);
  /* local port does not take effect until the WiFly has rebooted (2.32) */
  wifly.save();
  Serial.println(F("Set port to 80, rebooting to make it work"));
  wifly.reboot();
  delay(3000);
    }
    Serial.println(F("Ready"));
}

void loop()
{
  if (wifly.available() > 0) 
 {

       
        /* See if there is a request */
  if (wifly.gets(buf, sizeof(buf))) 
  { //se o wifly recebe alguma coisa
      if (strncmp_P(buf, PSTR("GET / "), 6) == 0) 
      { // if it`s a get do the next line
          /* GET request */
          Serial.println(F("Got GET request"));
          while (wifly.gets(buf, sizeof(buf)) > 0) 
          {
          /* Skip rest of request */
          }
          sendIndex(); //enviar a pagina principal
          Serial.println(F("Sent index page"));
          
      } 
      else if (strncmp_P(buf, PSTR("GET /on"), 7) == 0) //testa e o buf é igual a get/on
      { //abre bloco liga led
                  while (wifly.gets(buf, sizeof(buf)) > 0) 
                  {
                  
                  }
                  wifly.flushRx(); 
                  mostra_valores();
                  digitalWrite(3,HIGH);
                 Serial.println(F("ligando led"));
                 
      } //fecha bloco desliga led
      else if (strncmp_P(buf, PSTR("GET /off"), 8) == 0) //testa e o buf é igual a get/off
      { //abre bloco desliga led
                 while (wifly.gets(buf, sizeof(buf)) > 0) 
                  {
                  
                  }
                 wifly.flushRx(); 
                 mostra_valores();
                 digitalWrite(3,LOW); // e buf for igual a get/off desliga o led
                 Serial.println(F("desligando led"));
      } //fecha bloco desliga led */
      else if (strncmp_P(buf, PSTR("GET /ajax_swicht"), 16) == 0) //testa e o buf é igual a get/ajax_switch
      { //abre bloco ajax
                 while (wifly.gets(buf, sizeof(buf)) > 0) 
                  {
                  
                  }
                 wifly.flushRx(); 
                 mostra_valores(); //envia o valores
                
                 Serial.println(F("enviando valores"));
      } //fecha bloco ajax       
       else { //abre else
                
                Serial.print(F("Unexpected: "));
                Serial.println(buf);
                wifly.flushRx();    // discard rest of input
                Serial.println(F("Sending 404"));
                send404();       
             } //fecha else
  } //fecha o bloco de recebimento do wifly
 }//fecha e o wifly eta disponivel
} //fecha o void loop

/** Send an index HTML page with an input box for a username */
void sendIndex()
{
  /* Send the header direclty with print */
  wifly.println(F("HTTP/1.1 200 OK"));
  wifly.println(F("Content-Type: text/html"));
  wifly.println(F("Transfer-Encoding: chunked"));
  wifly.println(F("Connection: keep-alive"));
  wifly.println("\r\n");
  wifly.println();

  /* Send the body using the chunked protocol so the client knows when
   * the message is finished.
   * Note: we're not simply doing a close() because in version 2.32
   * firmware the close() does not work for client TCP streams.
   */
  wifly.sendChunkln(F("<html>"));
  wifly.sendChunkln(F("<head>"));
  wifly.sendChunkln(F("<title>engeBOT-WiFly HTTP Server Example</title>"));
  //começa script do ajax
  wifly.sendChunkln(F("<script>"));
  //funçao que manda os dado para o servidor web
  wifly.sendChunkln(F("function GetSwitchState(url)"));
  wifly.sendChunkln(F("{"));
  wifly.sendChunkln(F("nocache = \"&nocache=\" + Math.random() * 1000000;"));
  wifly.sendChunkln(F("var request = new XMLHttpRequest();"));
  wifly.sendChunkln(F("request.onreadystatechange = function()"));
  wifly.sendChunkln(F("{"));
  wifly.sendChunkln(F("if(this.readyState == 4) {"));
  wifly.sendChunkln(F("if(this.status == 200) {"));
  wifly.sendChunkln(F("if (this.responseText != null) {"));
  wifly.sendChunkln(F("document.getElementById(\"valores\").innerHTML = this.responseText;"));
  wifly.sendChunkln(F("}"));
  wifly.sendChunkln(F("}"));
  wifly.sendChunkln(F("}"));
  wifly.sendChunkln(F("}"));
  wifly.sendChunkln(F("request.open(\"GET\", url , false);"));
//  wifly.sendChunkln(F("request.open(\"GET\", \"ajax_swicht\", false);"));
  wifly.sendChunkln(F("request.send(null);"));
  wifly.sendChunkln(F("setTimeout('GetSwitchState(\"ajax_swicht\")', 1000);"));
  wifly.sendChunkln(F("}"));
  
  wifly.sendChunkln(F("</script>"));
  wifly.sendChunkln(F("</head>"));

  wifly.sendChunkln(F("<body onload=\"GetSwitchState('ajax_swicht')\">"));

  //   wifly.sendChunkln (F("<center><img src=http://imagizer.imageshack.us/v2/320x240q90/912/SduFv5.png></center>"));

  wifly.sendChunkln(F("<h1>"));
  wifly.sendChunkln(F("<center>"));
  wifly.sendChunkln(F("<p>Inovacao Sustentavel e Inteligente.</p>"));
  wifly.sendChunkln(F("</h1>"));
  wifly.sendChunkln (F("</br>"));
  wifly.sendChunkln(F("</center>"));
  wifly.sendChunkln(F("<center>"));
  wifly.sendChunkln(F(" <button type=\"button\" onclick=\"GetSwitchState('on')\">on</button>"));
  wifly.sendChunkln(F(" <button type=\"button\" onclick=\"GetSwitchState('off')\">off</button>"));
  wifly.sendChunkln(F("<div id=\"valores\">"));
  wifly.sendChunkln(F("</div>"));
  wifly.sendChunkln (F("</br>"));
  wifly.sendChunkln(F("</center>"));
  wifly.sendChunkln(F("</br>"));
  wifly.sendChunkln(F("</body>"));
  wifly.sendChunkln(F("</html>"));
  wifly.sendChunkln();
}
   
     
   

   
/** Send a 404 error */
void send404()
{
    wifly.println(F("HTTP/1.1 404 Not Found"));
    wifly.println(F("Content-Type: text/html"));
    wifly.println(F("Transfer-Encoding: chunked"));
    wifly.println();
    wifly.sendChunkln(F("<html><head>"));
    wifly.sendChunkln(F("<title>404 nao encontrada !!!</title>"));
    wifly.sendChunkln(F("</head><body>"));
    wifly.sendChunkln(F("<h1>Not Found</h1>"));
    wifly.sendChunkln(F("<hr>"));
    wifly.sendChunkln(F("</body></html>"));
    wifly.sendChunkln();
}

//mostra valores
void mostra_valores()
  {
         wifly.println(F("HTTP/1.1 200 OK"));
         wifly.println(F("Content-Type: text/html"));
         wifly.println(F("Transfer-Encoding: chunked"));
         wifly.println(F("Connection: keep-alive"));
         wifly.println();
 
        snprintf_P(buf, sizeof(buf), PSTR("<center><p>VALOR DO POTENCIOMETRO DO PINO 5=%d</p></center>"), analogRead(A5));
        wifly.sendChunkln(buf);
    
        snprintf_P(buf, sizeof(buf), PSTR("<center><p>VALOR DO POTENCIOMETRO DO PINO 4=%d</p></center>"), analogRead(A4));
        wifly.sendChunkln(buf);
    
        snprintf_P(buf, sizeof(buf), PSTR("<center><p>VALOR DA TEMP PINO 3=%d</p></center>"), analogRead(A3));
        wifly.sendChunkln(buf);
    
        snprintf_P(buf, sizeof(buf), PSTR("<center><p>LUMINOSIDADE PINO 2=%d</center></p>"), analogRead(A2));
        wifly.sendChunkln(buf);

        if ( digitalRead(8))
        {
          wifly.sendChunk("BOTÃO 1= LIGADO<BR>");
        }
        else 
        {
          wifly.sendChunk("BOTÃO 1= DESLIGADO<BR>");
          Serial.print(F("75."));
        }
        if ( digitalRead(7)) 
        {
          wifly.sendChunk("BOTÃO 2= LIGADO<BR>");
          Serial.print(F("85."));
        }
        else 
        {
          wifly.sendChunk("BOTÃO 2= DESLIGADO<BR>");
        }
         
        wifly.sendChunkln(); // finaliza comunicação html
  }

**Comment by harlequin-tech** [comment]
Problem is not related to the WiFlyHQ library, general programming issue.
